"""RAG evaluation module."""

import json
import logging
from typing import Dict, Any, Optional

from rag.llm_client import groq_client

logger = logging.getLogger(__name__)


class RAGEvaluator:
    """Evaluates RAG pipeline responses using LLM-based metrics."""
    
    @staticmethod
    def evaluate_query(
        query: str,
        context: str,
        answer: str,
        query_type: str
    ) -> Dict[str, Any]:
        """
        Evaluate a single response for relevance, correctness, and faithfulness.
        
        Args:
            query: The user's query
            context: Retrieved context (documents, web data, or KG data) used for the answer
            answer: The generated answer to evaluate
            query_type: The source routing type ('rag', 'kg', 'web', 'direct', etc.)
            
        Returns:
            Dict containing evaluation scores (1.0 to 5.0) and explanations
        """
        # Default fallback values
        default_eval = {
            "faithfulness": 5.0,
            "faithfulness_explanation": "Not evaluated.",
            "context_relevance": 5.0,
            "context_relevance_explanation": "Not evaluated.",
            "answer_correctness": 5.0,
            "answer_correctness_explanation": "Not evaluated."
        }
        
        # If it's a direct LLM query without any context, only correctness is applicable
        context_is_empty = not context.strip() if context else True
        
        system_prompt = """You are an independent AI quality evaluation agent. You are evaluating a response generated by an intelligent chatbot.
You must grade the chatbot's performance on three key metrics on a scale of 1.0 to 5.0 (where 1.0 is extremely poor, and 5.0 is perfect).

Metrics to evaluate:
1. **faithfulness**:
   - Measures if the generated answer is completely grounded in and supported ONLY by the provided context.
   - Look for hallucinations, external assumptions, or claims not found in the context.
   - If there is NO context (or context is empty), return a score of 5.0 and note that context was not provided.

2. **context_relevance**:
   - Measures if the retrieved context contains information relevant, focused, and necessary to answer the user query.
   - Penalize redundant, unrelated, or noisy text in the context.
   - If there is NO context, return a score of 5.0 and note that context was not provided.

3. **answer_correctness**:
   - Measures how accurately, directly, and completely the generated answer addresses the user query.
   - Is the response correct, logical, and helpful?

You MUST respond ONLY with a valid JSON object. Do not include any markdown styling like ```json or ```, and do not write any introductory or concluding text.

JSON Schema:
{
  "faithfulness": float (1.0 to 5.0),
  "faithfulness_explanation": "Explanation of the faithfulness grade.",
  "context_relevance": float (1.0 to 5.0),
  "context_relevance_explanation": "Explanation of the context relevance grade.",
  "answer_correctness": float (1.0 to 5.0),
  "answer_correctness_explanation": "Explanation of the answer correctness grade."
}"""

        user_content = f"""User Query: {query}
Query Type: {query_type}
Retrieved Context: {context if not context_is_empty else "[NO CONTEXT]"}
Generated Answer: {answer}"""

        try:
            # Prepare messages
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content}
            ]
            
            # Request response in JSON format from Groq
            # Since settings config has temperature and model, we use groq_client
            # Note: We use a low temperature (e.g. 0.1) for consistent evaluation results
            logger.info("Sending RAG evaluation request to GROQ API")
            raw_response = groq_client.client.chat.completions.create(
                model=groq_client.model,
                messages=messages,
                temperature=0.1,
                response_format={"type": "json_object"}
            )
            
            response_text = raw_response.choices[0].message.content.strip()
            
            # Parse the JSON response
            evaluation_result = json.loads(response_text)
            
            # Validate structure and keys
            required_keys = [
                "faithfulness", "faithfulness_explanation",
                "context_relevance", "context_relevance_explanation",
                "answer_correctness", "answer_correctness_explanation"
            ]
            
            if all(key in evaluation_result for key in required_keys):
                # Ensure scores are within 1.0 to 5.0 range
                for key in ["faithfulness", "context_relevance", "answer_correctness"]:
                    try:
                        val = float(evaluation_result[key])
                        evaluation_result[key] = max(1.0, min(5.0, val))
                    except (ValueError, TypeError):
                        evaluation_result[key] = 5.0
                return evaluation_result
            else:
                logger.warning(f"Evaluation response missing keys. Response was: {response_text}")
                return default_eval
                
        except Exception as e:
            logger.error(f"Error executing RAG evaluation: {e}")
            return default_eval
